### ISSUE TITLE
Calculate Ktrans

### ISSUE THREAD

**Issue by elijahrockers** [petmri/ROCKETSHIP#1]
Hello, I am trying to find a software to calculate Ktrans with. I have DCE data that has already been fit to T1 and have even calculated the concentration map for the entire time series, but I'm having trouble finding software to calculate Ktrans. I would like to be able to input an arterial input function also. Does ROCKETSHIP have this capability? If not can you suggest a solution for me in the meantime?

Thanks,
Eli

**Comment by ironictoo** [comment]
Rocketship could do this but not directly, you would need to write some Matlab code. You could modify Rocketship not to perform the concentration calculations, and just take your input data as the concentration map. Or you could create a .MAT file with the appropriate data structures and feed it into Rocketship "Part D" as the "Part B" results. That would require a bit of reverse engineering to figure out how to structure the data. I'm not sure which would be easier. 

I don't know of any other software that would do what you want out of the box, as far as I know they are all setup to create the concentration curves, and splicing your data into the middle of the processing pipeline is going to require some programming.
Good luck!
 

    On Friday, January 22, 2016 11:57 AM, elijahrockers <notifications@github.com> wrote:
 

 Hello, I am trying to find a software to calculate Ktrans with I have DCE data that has already been fit to T1 and have even calculated the concentration map for the entire time series, but I'm having trouble finding software to calculate Ktrans I would like to be able to input an arterial input function also Does ROCKETSHIP have this capability? If not can you suggest a solution for me in the meantime?Thanks,
Eli—

**Comment by elijahrockers** [comment]
I could even start from ground zero, I have the DCE data, preinjection multi-flip angle T1 scan, and can even get a customized AIF.

When I tried to load the DCE data in "part A" however, MATLAB informs me that my X and Y dimensions are not the same (which they are as far as I know)

**Comment by ironictoo** [comment]
Is your data in nifti format? Rocketship will want a t1 map and the dynamic data series, you can make the t1 map with the parametric scripts that come with it. See the wiki for a walk through. 

Sam
