### ISSUE TITLE
AIF

### ISSUE THREAD

**Issue by elijahrockers** [petmri/ROCKETSHIP#10]
I am trying to find more details on how AIF identification happens. For example, I notice the program identified 600 or so voxels as being AIF voxels. How does it come to this conclusion?

**Comment by elijahrockers** [comment]
Additionally, when running part B, we can see a fitted curve (or raw AIF curve depending on selection) overlaid on the original plasma curve data. Is there anyway to access this data? I have looked at Adata and Bdata, but I'm not sure if that curve is represented as an element in either of these structures.

Basically I would like to get the AIF separately as a vector.

**Comment by elijahrockers** [comment]
Sobel filter... got it... although it there are any more details I would appreciate it

**Comment by ironictoo** [comment]
For how it selects the AIF there are three criteria, 

1)	Must have a r^2 fit to the bi-exponential model of >0.8
2)	The signal at the last measurement point must be <0.45 of the peak signal
3)	Must have a sobel derivative of <0.005 (indicates a sharp rise) at injection

The values for all of these criteria can be adjusted in the dce_preferences.txt file. These worked fairly well for my datasets/temporal resolution/injection protocol, but may not work for others.
