### ISSUE TITLE
No independent variables entered

### ISSUE THREAD

**Issue by ineffiableyc** [petmri/ROCKETSHIP#14]
Hi:

I am still new to this. I was trying to use test data to generate T1 map using run_parametric.m, the error it gave me is "no independent variables entered". My setting is as below:
![screenshot 2016-07-24 11 39 54](https://cloud.githubusercontent.com/assets/20627366/17085037/653a69e8-5193-11e6-8b1c-d72d29ba641e.png)

btw:
how can i enlarge the font? it is very difficult to read.
sorry if my question is too silly. Thanks!

best

nellie

**Comment by ironictoo** [comment]
Sorry I missed this. You need to enter the fa in the "value list" box, i.e. "2,5,10"
