### ISSUE TITLE
Negative time curves generated in RUNA 

### ISSUE THREAD

**Issue by 20zzyw** [petmri/ROCKETSHIP#15]
Thanks for your work. As it ran the first step, i found 17 continous negative point representing the last 17 phases (20 in total) on time curves of R1maps, delta R1 ROI and Ct maps though it worked well using provided test data (BBB data p19).
![2018-06-20_203742](https://user-images.githubusercontent.com/18713742/41658705-d1467496-74c9-11e8-8916-889b60900b8d.jpg)

The acquisition parameters of my data were: 
3D-LAVA (Fat Suppressed, GE 3.0T) 20 phases, TR 3.6ms, FA=15 degrees.
The first phase of LAVA (without contrast agent) was regarded as the T1map regarless of its poor SNR.

Could you please provide any solution, or figure out the reason of this issue?

==============================================================
Alright I found there were many negative R1 value which should be a natural-born positive value in tumor ROI (line 661-708, A_make_R1maps_func.m). After I replaced variable "R1tTOI" with its absolute values, the time curve seemed much more normal.
![2018-06-21_005220](https://user-images.githubusercontent.com/18713742/41672782-6a4e349e-74ed-11e8-967a-78aa0ebc67f0.jpg)

But I don't know whether this approach is reasonable or not.

Best regards

**Comment by ironictoo** [comment]
This was resolved some time ago, it was just a display issue for averaging (mean) in noisy pixels from the background that had large negative values.
