### ISSUE TITLE
Which one of the models (if any) can be used to fit renal DCE-MRI data?

### ISSUE THREAD

**Issue by mscipio** [petmri/ROCKETSHIP#16]
As the tile says, do you have implemented any model to fit the kinetic of the renal cortex?

**Comment by ironictoo** [comment]
I've never personally used it in that application, but one of the standard models probably applies. Maybe extended Tofts? Or 2cxm?
    On Friday, March 27, 2020, 02:15:21 PM PDT, Michele Scipioni <notifications@github.com> wrote:  
 
 


As the tile says, do you have implemented any model to fit the kinetic of the renal cortex?
