### ISSUE TITLE
Errors in RUND of the DCE module

### ISSUE THREAD

**Issue by Logan-416** [petmri/ROCKETSHIP#18]
Hi, did anyone encounter the following errors when running the RUND step of the DCE module (Matlab version R2017a)? It seems that several relevant files are missing. 

> Starting Part D - Fitting Voxels/ROIs
> 04-Feb-2021 15:13:15
>  
>   
> Begin making maps for patlak...
> Starting fitting for 25497 voxels...
> Undefined variable "ModelID" or class "ModelID.PATLAK".
> Error in FXLfit_generic (line 734)
>         model_id = ModelID.PATLAK;
> Error in D_fit_voxels_func (line 568)
>             [fitting_results, voxel_residuals] = FXLfit_generic(xdata,
>             numvoxels, cur_dce_model);
> Error in RUND>done_Callback (line 323)

**Comment by kinga3** [comment]
I have had a similar issue using the Extended Tofts model but have had no luck fixing it:

Undefined variable "ModelID" or class "ModelID.TOFTS_EXTENDED".
Error in FXLfit_generic (line 87)
        model_id = ModelID.TOFTS_EXTENDED;
Error in D_fit_voxels_func (line 568)
            [fitting_results, voxel_residuals] = FXLfit_generic(xdata, numvoxels,
            cur_dce_model);
Error in RUND>done_Callback (line 323)

Did you get anywhere with fixing this? Would appreciate any help!

**Comment by Logan-416** [comment]
> I have had a similar issue using the Extended Tofts model but have had no luck fixing it:
> 
> Undefined variable "ModelID" or class "ModelID.TOFTS_EXTENDED".
> Error in FXLfit_generic (line 87)
> model_id = ModelID.TOFTS_EXTENDED;
> Error in D_fit_voxels_func (line 568)
> [fitting_results, voxel_residuals] = FXLfit_generic(xdata, numvoxels,
> cur_dce_model);
> Error in RUND>done_Callback (line 323)
> 
> Did you get anywhere with fixing this? Would appreciate any help!

Unfortunately, not yet. Maybe we should copy files from someone else who downloaded these codes earlier.

**Comment by kinga3** [comment]
When I re-downloaded ROCKETSHIP, I believe the latest version, the folder called "parametric_scripts" is empty and I no longer get this error, not sure how it solved the issue but my Run D is completing now. Also, are you sure you have the correct folder and all subfolders added to your MATLAB path?

**Comment by Davi05d** [comment]
Hi, 
I have an issue probably similar to yours. On Matlab R2020b:
Unable to resolve the name ModelID.TOFTS.
Error in FXLfit_generic (line 378)
        model_id = ModelID.TOFTS;

It looks to me like something is missing somewhere. I redownloaded all files available here (it states ROCKETSHIP DCE v1.2 2016) with no change. Is it possible that some parts of the tool are missing, or might it be a code-driven bug?

Thank you for any hints to solve this problem
Kind regards
David

**Comment by Logan-416** [comment]
> When I re-downloaded ROCKETSHIP, I believe the latest version, the folder called "parametric_scripts" is empty and I no longer get this error, not sure how it solved the issue but my Run D is completing now. Also, are you sure you have the correct folder and all subfolders added to your MATLAB path?

Congratulations! Sorry for my late reply. Yes, all folders were added in the MATLAB path. The error still exists even though I redownloaded these files. Finally, I copied an old version of ROCKETSHIP from someone else. And it works well now.

**Comment by Logan-416** [comment]
> Hi,
> I have an issue probably similar to yours. On Matlab R2020b:
> Unable to resolve the name ModelID.TOFTS.
> Error in FXLfit_generic (line 378)
> model_id = ModelID.TOFTS;
> 
> It looks to me like something is missing somewhere. I redownloaded all files available here (it states ROCKETSHIP DCE v1.2 2016) with no change. Is it possible that some parts of the tool are missing, or might it be a code-driven bug?
> 
> Thank you for any hints to solve this problem
> Kind regards
> David

Hi, 
I guess some files are missing.  I copied an old version of ROCKETSHIP from someone else. It works well on Matlab R2017a. I can send it to you if you need it.

**Comment by Davi05d** [comment]
> > Hi,
> > I have an issue probably similar to yours. On Matlab R2020b:
> > Unable to resolve the name ModelID.TOFTS.
> > Error in FXLfit_generic (line 378)
> > model_id = ModelID.TOFTS;
> > It looks to me like something is missing somewhere. I redownloaded all files available here (it states ROCKETSHIP DCE v1.2 2016) with no change. Is it possible that some parts of the tool are missing, or might it be a code-driven bug?
> > Thank you for any hints to solve this problem
> > Kind regards
> > David
> 
> Hi,
> I guess some files are missing. I copied an old version of ROCKETSHIP from someone else. It works well on Matlab R2017a. I can send it to you if you need it.

That would be great. Can you send it to david.kala@fgu.cas.cz, please? I would be grateful.

**Comment by Logan-416** [comment]
> > > Hi,
> > > I have an issue probably similar to yours. On Matlab R2020b:
> > > Unable to resolve the name ModelID.TOFTS.
> > > Error in FXLfit_generic (line 378)
> > > model_id = ModelID.TOFTS;
> > > It looks to me like something is missing somewhere. I redownloaded all files available here (it states ROCKETSHIP DCE v1.2 2016) with no change. Is it possible that some parts of the tool are missing, or might it be a code-driven bug?
> > > Thank you for any hints to solve this problem
> > > Kind regards
> > > David
> > 
> > 
> > Hi,
> > I guess some files are missing. I copied an old version of ROCKETSHIP from someone else. It works well on Matlab R2017a. I can send it to you if you need it.
> 
> That would be great. Can you send it to [david.kala@fgu.cas.cz](mailto:david.kala@fgu.cas.cz), please? I would be grateful.

Sure, you are welcome :)

**Comment by Davi05d** [comment]
> > > > Hi,
> > > > I have an issue probably similar to yours. On Matlab R2020b:
> > > > Unable to resolve the name ModelID.TOFTS.
> > > > Error in FXLfit_generic (line 378)
> > > > model_id = ModelID.TOFTS;
> > > > It looks to me like something is missing somewhere. I redownloaded all files available here (it states ROCKETSHIP DCE v1.2 2016) with no change. Is it possible that some parts of the tool are missing, or might it be a code-driven bug?
> > > > Thank you for any hints to solve this problem
> > > > Kind regards
> > > > David
> > > 
> > > 
> > > Hi,
> > > I guess some files are missing. I copied an old version of ROCKETSHIP from someone else. It works well on Matlab R2017a. I can send it to you if you need it.
> > 
> > 
> > That would be great. Can you send it to [david.kala@fgu.cas.cz](mailto:david.kala@fgu.cas.cz), please? I would be grateful.
> 
> Sure, you are welcome :)

It's running now (with the old version)! Thanks a lot

**Comment by Logan-416** [comment]
> > > > > Hi,
> > > > > I have an issue probably similar to yours. On Matlab R2020b:
> > > > > Unable to resolve the name ModelID.TOFTS.
> > > > > Error in FXLfit_generic (line 378)
> > > > > model_id = ModelID.TOFTS;
> > > > > It looks to me like something is missing somewhere. I redownloaded all files available here (it states ROCKETSHIP DCE v1.2 2016) with no change. Is it possible that some parts of the tool are missing, or might it be a code-driven bug?
> > > > > Thank you for any hints to solve this problem
> > > > > Kind regards
> > > > > David
> > > > 
> > > > 
> > > > Hi,
> > > > I guess some files are missing. I copied an old version of ROCKETSHIP from someone else. It works well on Matlab R2017a. I can send it to you if you need it.
> > > 
> > > 
> > > That would be great. Can you send it to [david.kala@fgu.cas.cz](mailto:david.kala@fgu.cas.cz), please? I would be grateful.
> > 
> > 
> > Sure, you are welcome :)
> 
> It's running now (with the old version)! Thanks a lot

**Comment by Logan-416** [comment]
> > > > > > Hi,
> > > > > > I have an issue probably similar to yours. On Matlab R2020b:
> > > > > > Unable to resolve the name ModelID.TOFTS.
> > > > > > Error in FXLfit_generic (line 378)
> > > > > > model_id = ModelID.TOFTS;
> > > > > > It looks to me like something is missing somewhere. I redownloaded all files available here (it states ROCKETSHIP DCE v1.2 2016) with no change. Is it possible that some parts of the tool are missing, or might it be a code-driven bug?
> > > > > > Thank you for any hints to solve this problem
> > > > > > Kind regards
> > > > > > David
> > > > > 
> > > > > 
> > > > > Hi,
> > > > > I guess some files are missing. I copied an old version of ROCKETSHIP from someone else. It works well on Matlab R2017a. I can send it to you if you need it.
> > > > 
> > > > 
> > > > That would be great. Can you send it to [david.kala@fgu.cas.cz](mailto:david.kala@fgu.cas.cz), please? I would be grateful.
> > > 
> > > 
> > > Sure, you are welcome :)
> > 
> > 
> > It's running now (with the old version)! Thanks a lot

Congrats!

**Comment by jamesmz285** [comment]
Hi, is there any way I can get access to this older version that was mentioned above? I have the same problem right now.

Thank you very much!

**Comment by Logan-416** [comment]
> Hi, is there any way I can get access to this older version that was mentioned above? I have the same problem right now.
> 
> Thank you very much!

Hi, maybe I can send it to your email~

**Comment by jamesmz285** [comment]
> > Hi, is there any way I can get access to this older version that was mentioned above? I have the same problem right now.
> > Thank you very much!
> 
> Hi, maybe I can send it to your email~

Very appreciated! 
Would you send it to mz31@illinois.edu

**Comment by Logan-416** [comment]
> > > Hi, is there any way I can get access to this older version that was mentioned above? I have the same problem right now.
> > > Thank you very much!
> > 
> > 
> > Hi, maybe I can send it to your email~
> 
> Very appreciated!
> Would you send it to [mz31@illinois.edu](mailto:mz31@illinois.edu)

Sure. You can have a try with the old version now.

**Comment by jamesmz285** [comment]
> > > > Hi, is there any way I can get access to this older version that was mentioned above? I have the same problem right now.
> > > > Thank you very much!
> > > 
> > > 
> > > Hi, maybe I can send it to your email~
> > 
> > 
> > Very appreciated!
> > Would you send it to [mz31@illinois.edu](mailto:mz31@illinois.edu)
> 
> Sure. You can have a try with the old version now.

Hi Logan. I just realized that my institute might have banned attaching .zip files to emails, so I only received the text of your email. I've been hesitating, but could you send it again to jamesmz1995@gmail.com since gmail should not ban zip files? Thanks again...

**Comment by Logan-416** [comment]
> > > > > Hi, is there any way I can get access to this older version that was mentioned above? I have the same problem right now.
> > > > > Thank you very much!
> > > > 
> > > > 
> > > > Hi, maybe I can send it to your email~
> > > 
> > > 
> > > Very appreciated!
> > > Would you send it to [mz31@illinois.edu](mailto:mz31@illinois.edu)
> > 
> > 
> > Sure. You can have a try with the old version now.
> 
> Hi Logan. I just realized that my institute might have banned attaching .zip files to emails, so I only received the text of your email. I've been hesitating, but could you send it again to [jamesmz1995@gmail.com](mailto:jamesmz1995@gmail.com) since gmail should not ban zip files? Thanks again...

No problem. You're welcome:)

**Comment by jamesmz285** [comment]
I finally got the attachment. Much appreciated!

**Comment by Logan-416** [comment]
> I finally got the attachment. Much appreciated!

OK, you can test it now!

**Comment by jamesmz285** [comment]
It perfectly worked this time! Thank you very much, Logan.

**Comment by Logan-416** [comment]
> It perfectly worked this time! Thank you very much, Logan.

Congrats! My pleasure :)

**Comment by weijunhuashan** [comment]
> > When I re-downloaded ROCKETSHIP, I believe the latest version, the folder called "parametric_scripts" is empty and I no longer get this error, not sure how it solved the issue but my Run D is completing now. Also, are you sure you have the correct folder and all subfolders added to your MATLAB path?
> 
> Congratulations! Sorry for my late reply. Yes, all folders were added in the MATLAB path. The error still exists even though I redownloaded these files. Finally, I copied an old version of ROCKETSHIP from someone else. And it works well now.

I have the same problem,  Can you please send a copy to weijun_tang@fudan.edu.cn? I would be grateful.

**Comment by lsaca05** [comment]
Greetings,

By default GPU use/fitting is enabled in `dce_preferences.txt` and thus requires the [gpufit](https://github.com/ironictoo/Gpufit) library, which contains `ModelID`. To eliminate this requirement and use the CPU (like the old version) set `gpu_use = 0` in `dce/dce_preferences.txt`.

I think I may change it to CPU by default or have it auto-detect the GPU setting to prevent confusion.
