### ISSUE TITLE
parametric_scripts folder is empty

### ISSUE THREAD

**Issue by jsother** [petmri/ROCKETSHIP#19]
Attempts to download code, either by ZIP or GIT, shows "parametric_scripts" folder is empty and "Parametric Fitting" cannot proceed e.g.  "Unrecognized function or variable 'fitting_gui'  "

**Comment by ironictoo** [comment]
parametric_scripts is a submodule. The easiest way to get it, is to use the -recursive option on the original git clone, ie:

git clone --recursive https://github.com/petmri/ROCKETSHIP.git

Alternatively you can get it [here](https://github.com/petmri/parametric_scripts)

**Comment by ironictoo** [comment]
There was an issue here where some commits of ROCKETSHIP referred to commits of the parametric_scripts submodule that were not on github, which would cause it to fail to download. This has been resolved in the latest version.
We are also in the processes of switching parametric_scripts from a submodule to a subtree, but that won't hit the master branch for a little while.
