### ISSUE TITLE
Error: "Unable to resolve the name ModelID.TOFTS."

### ISSUE THREAD

**Issue by jdullea** [petmri/ROCKETSHIP#22]
Hello, 

In running the "Run D" module on DCE data, I get the error copied below. There were no issues prior to this point ("Run A" -> "Run B") which leads me to believe that it is not an error with what is included in the environment. I have not been able to find an answer in searching through forums. I was hoping that would would be able to provide guidance.

Thank you!

Unable to resolve the name ModelID.TOFTS.

Error in FXLfit_generic (line 378)
        model_id = ModelID.TOFTS;

Error in D_fit_voxels_func (line 554)
            [roi_results, roi_residuals] = FXLfit_generic(roi_data, number_rois, cur_dce_model);

Error in RUND>done_Callback (line 323)
saved_results = D_fit_voxels_func(results_b_path,dce_model,time_smoothing,time_smoothing_window,xy_smooth_size,number_cpus,roi_list,fit_voxels,neuroecon, outputft);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in RUND (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)RUND('done_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**Comment by tomasvikner** [comment]
Hello, 

Got the same issue but for the Patlak model. 

"Unable to resolve the name ModelID.PATLAK."

Did you find a solution?

**Comment by tomasvikner** [comment]
Hello,

Had the same issue but for the Patlak model. Setting "gpu_use = 0" in the "dce_preferences.txt" file solved it for me (I don't have a NVIDIA GPU).

**Comment by lsaca05** [comment]
Greetings,

By default GPU use/fitting is enabled and thus requires the [gpufit](https://github.com/ironictoo/Gpufit) library, which contains the ModelID. The above solution by @tomasvikner eliminates this requirement by using the CPU.

Might change it to CPU by default or have it auto-detect the GPU setting.
