### ISSUE TITLE
fitting_gui

### ISSUE THREAD

**Issue by doctorbulat** [petmri/ROCKETSHIP#3]
Please help me to get t1 map.
I have 2 series with various flip angles: 2 degrees and 15 degrees.
I have to add two different .nii files for FA=2 degrees and FA=15 degrees (separately). Am i right?
Then in Data order i have to put "x,y,z/file". Am I right? I don't understand what does 'data order' mean from the wiki...
And what parameter values I have to put into TE/TR/FA/TI/B Value list? I put "1.7,5.1,2,15", because I have TE=1.7, TR=5.1, FA1=2, FA2=15 degrees.  And why I have to write TR parameter for the second time after TE/TR/FA/TI/B Value list?
Then I put "T1 multi FA Exponential".
But I have a mistake, because the programm writes "wrong number of parameters"...
Sorry for my bad english.
Best regards,
Bulat.

**Comment by doctorbulat** [comment]
"Data order is how the data is arranged, say both of your flip angles were in a single file then the order would be "x,y,z,n". For your case "x,y,z/file" is correct.
For TE/TR/FA/TI/B Value list you could put "2, 15" and that is it. You only put down the variable that is changing. The others (TE, TR, etc.) would be for other mapping techniques.
T1 FA Exponential sounds correct."
Thank you for the answer! 
I put all variables but have some problems in matlab command window (matlab 2012a, all required toolboxes are present):

"Undefined function 'gcp' for input arguments of type 'char'.

Error in calculateMap (line 204)
        s = gcp('nocreate');

Error in calculateMap_batch (line 170)
        [single_IMG, errormsg] = calculateMap(CUR_JOB);

Error in fitting_gui>run_estimate_Callback (line 856)
    [single_IMG , ~ , ~, errormsg] = calculateMap_batch(JOB_struct, submit, batch_selected);

Error in gui_mainfcn (line 96)
        feval(varargin{:});

Error in fitting_gui (line 43)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)fitting_gui('run_estimate_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uicontrol Callback "

May it be the problem with matlab2012?

**Comment by ironictoo** [comment]
In the file dce_preferences.txt change the line
% True for version R2013a and older
use_matlabpool = 0

to be 1. That will fix the immediate problem, but there may be other issues with that version (I haven't tested it). Let me know if it works so I can update the list of which versions are compatible. 

Sam

**Comment by doctorbulat** [comment]
Thanks a lot! I wil try it tomorrow on R2012 and write results.
But today I tried to do it on my colleague's R2014a version. The calculation of r^2 map is ok, but when I push "submit job" I have mistakes in command window:

run_parametric
Warning: MATLAB Toolbox Path Cache is out of date and is not being used.
Type 'help toolbox_path_cache' for more info
Warning: Name is nonexistent or not a directory:
D:\ROCKETSHIP-master\parametric_scripts
> In path at 109
  In addpath at 86
  In run_parametric at 6
User selected r^2 threshold:
    0.6000

User selected Submit Jobs
Starting execution at January 28, 2016 23:08:36
User selected files:
C:\Program Files (x86)\Merge Healthcare\eFilm\CD\t1_vibe_tra_pre_flip_2deg.nii
C:\Program Files (x86)\Merge Healthcare\eFilm\CD\t1_vibe_tra_pre_flip_15deg.nii
User selected TE/TR/FA/TI:
     2
    15

User selected fit:
t1_fa_fit
User selected CPUs:
     2

User selected Neuroecon:
     0

User selected email:
User selected data order:
xyzfile
User selected output basename:
T1_map
User selected only odd echoes:
     0

User selected smooth size (Gaussian standard deviation):
     0

User selected fit all voxels:
     1

User selected ROIs:
User selected tr:
    3.6000

User selected r^2 threshold:
    0.6000

Error using sfit/confint (line 36)
Cannot compute confidence intervals if #observations<=#coefficients.

Error in fitParameter (line 356)
        confidence_interval = confint(cf_,0.95);

Error in parallelFit>(parfor body) (line 38)
        fit_output(m,:) = fitParameter(parameter,fit_type,si,tr, fit_name, ncoeffs, coeffs,
        tr_present,rsquared_threshold);

Error in parallelFit (line 32)
    parfor m = n:min(n+(parallel_size-1),number_voxels)

Error in calculateMap (line 475)
            fit_output = parallelFit(parameter_list,fit_type,shaped_image,tr, submit, fit_file, ncoeffs, coeffs,
            tr_present,rsquared_threshold);

Error in calculateMap_batch (line 54)
            [single_IMG, errormsg_ind, CUR_JOB, new_txtname(done+1).txtname] = calculateMap(CUR_JOB, i);

Error in fitting_gui>ok_button_Callback (line 307)
[single_IMG submit data_setnum] = calculateMap_batch(JOB_struct, submit, dataset_to_process);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in fitting_gui (line 43)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)fitting_gui('ok_button_Callback',hObject,eventdata,guidata(hObject))

 
Error using javaMethodEDT
Error while evaluating uicontrol Callback

>>

**Comment by doctorbulat** [comment]
Hello!  In the file dce_preferences.txt I tried to change the line
% True for version R2013a and older
use_matlabpool = 0
to be 1.
The problem is not solved. The mistakes in command window are the same. So I will work on 2014a version.

**Comment by doctorbulat** [comment]
Hello again. On 2014a version I tried to put with "T1 multi FA linear" (not exponential as previous) and almost everything is ok. I got T1 map, but also had some problems. Send you text file.
[T1_map_t1_fa_fit_t1_vibe_tra_pre_flip_15deg.txt](https://github.com/petmri/ROCKETSHIP/files/109503/T1_map_t1_fa_fit_t1_vibe_tra_pre_flip_15deg.txt)

**Comment by doctorbulat** [comment]
excuse me! can you help me with my questions please!

**Comment by ironictoo** [comment]
I see the error message, but the T1 map is created ok? I can work to suppress the error message, but if you are getting a  T1 map that won't change. You can just ignore the error message and continue, or is something else not working?
 

    On Saturday, January 30, 2016 12:48 PM, doctorbulat <notifications@github.com> wrote:
 

 Hello again. On 2014a version I tried to put with "T1 multi FA linear" (not exponential as previous) and almost everything is ok. I got T1 map, but also had some problems. Send you text file.
T1_map_t1_fa_fit_t1_vibe_tra_pre_flip_15deg.txt—

**Comment by doctorbulat** [comment]
ok!
