### ISSUE TITLE
"not enough input arguments" in RUNA

### ISSUE THREAD

**Issue by HildevandenBrink** [petmri/ROCKETSHIP#32]
Dear all,

Using Rocketship RUNA I am running into a, what it seems, silly problem which I however am unable to solve.
I select all the files, set all parameters, but when I hit run, I immediately get an error.
Please see screenshot below.
 
How I interpret this, I think it seems that Rocketship can somehow not access my files.
I base this also on printscreens of other command windows on this forum, where I see that after "Loading image volumes" in the preparation steps, there are actually more lines of information about the AIF that are not in my output. 
I checked the following:
- The paths to the data are added in Matlab
- I tried using .nii files as well as .nii.gz files
- I checked that I have reading and writing access to the files...

I am out of ideas. Maybe something else is the actual problem underlying this, but I cannot figure it out.
I hope somebody may have a suggestion. 

I very much appreciate your help in advance.
Have a lovely day,
Hilde

![error](https://user-images.githubusercontent.com/125998097/220395150-6e5b309c-5dfa-40b9-b2fa-4dddc024dc62.PNG)

**Comment by lsaca05** [comment]
Greetings Hilde,

Can you provide a screenshot of the RUNA window, once it's ready to run?

**Comment by HildevandenBrink** [comment]
Of course!
Here it is. With these settings I replicate the exact same error message as above.

![print](https://user-images.githubusercontent.com/125998097/220758574-5065119d-3bf1-48ec-9699-4c3064772d6c.png)

**Comment by lsaca05** [comment]
If the issue is what I think it is, then you may be on an old version missing a fix I made about a month ago. Please verify that you on the latest version of the `master` branch.

**Comment by HildevandenBrink** [comment]
Thank you for your suggestion.
I deleted ROCKETSHIP and ran the git clone again to set it up.
The previous error is gone, but unfortunately there still seems to be an issue.
Does this new error help you in your previous reasoning about the possible underlying problem?
Thank you again,
Hilde

![print2](https://user-images.githubusercontent.com/125998097/220966078-49f3c3ba-6a7f-46cd-80b4-ea90f49a8764.png)

**Comment by HildevandenBrink** [comment]
Thank you again!
RUN A is running now. This issue is resolved.

**Comment by lsaca05** [comment]
> Thank you again! RUN A is running now. This issue is resolved.

Glad to hear it. Best of luck.
