### ISSUE TITLE
dce_run_A

### ISSUE THREAD

**Issue by doctorbulat** [petmri/ROCKETSHIP#4]
Hello again! I tried to run a. But have some troubles again. 
"Input image sizes not the same".

And second question about AIF/RR. How to make a binary mask, with 1 in the AIF/RR region and zero elsewhere; or a T1 map, where the AIF/RR region contains valid T1 values (in ms), and all other regions are zero? which programm should I use? Is there any manuals how to do them! And also how to select ROI? I think the solution is the same?
Thank you very much and sorry for so many problems!
Best regards,
Bulat.

**Comment by doctorbulat** [comment]
what is the problem with input dynamic datasets? how to do it right?

**Comment by doctorbulat** [comment]
I tried even to input coregistrated in spm images, but still i have "Input image sizes not the same"...

**Comment by ironictoo** [comment]
The input images have to be exactly the same size, there is no getting around that, they should be acquired that way in the first place. If they are off a little for some reason you can resample them with a program like ImageJ, that would probably be the easiest thing to do. But you need to make sure the anatomy lines up precisely if it is a little off you will get artifacts were anatomic structures don't line up.
To make the binary masks we used ImageJ, I recommend getting FIJI which is ImageJ with a bunch of nice plugins and an updater.
ImageJ can also be used to make ROI files.


 

    On Saturday, January 30, 2016 8:07 AM, doctorbulat <notifications@github.com> wrote:
 

 Hello again! I tried to run a But have some troubles again 
"Input image sizes not the same"
I checked the matrix size for dynamic datasets It is equal to 192x132
And matrix size t1_pre_flip_2deg and t1_pre_flip_15deg (images to get t1_map) It is equal to 192x138
Not a big difference between 132 and 138 Is that the solution for the problem? the matrix sizes must be absolutely the same?And second question about AIF/RR How to make a binary mask, with 1 in the AIF/RR region and zero elsewhere; or a T1 map, where the AIF/RR region contains valid T1 values (in ms), and all other regions are zero? which programm should I use? Is there any manuals how to do them! And also how to select ROI? I think the solution is the same?
Thank you very much and sorry for so many problems!
Best regards,
Bulat—

**Comment by ironictoo** [comment]
You going to have to be more specific about what problem you are having.
 

    On Monday, February 1, 2016 1:02 PM, doctorbulat <notifications@github.com> wrote:
 

 what is the problem with input dynamic datasets? how to do it right?—

**Comment by doctorbulat** [comment]
What about sequence? Can I use TWIST sequence (Siemens)? It is Time-resolved angiography With Interleaved Stochastic Trajectories. It is  conventional 3D gradient echo sequence (“fl3d_ce”).

**Comment by doctorbulat** [comment]
what picture do you use to get binary mask for AIF? Can it be from dynamic series? Or can I use 3D TOF angiography image? And what vessel do you use? Anterior cerebral artery? Internal carotid artery?

**Comment by doctorbulat** [comment]
When I download the dynamic MRI images do I have to download series of T1 images (in 1 serie I have 20 slices for example) or just from 1 serie I must download 1 slice (for examle 1 slice at the level of deep white matter)???

**Comment by doctorbulat** [comment]
Hello again! Today I tried to do DCE with VIBE sequence (Siemens). It is like fast SPGR on GE. The size of the t1 map images and dynamic series is the same. But still I have the problem that "Input image sizes not the same". I checked all parameters (matrix size, lining, all resolutions) - everything is the same... what am I doing wrong?

**Comment by doctorbulat** [comment]
![input image size not the same](https://cloud.githubusercontent.com/assets/16917116/12750743/27f9ec26-c9ca-11e5-85d2-99a41ba70580.jpg)

**Comment by doctorbulat** [comment]
I understand the problem... I can input only 1 slice, not all serie. It so simple. Am I right?

**Comment by doctorbulat** [comment]
I made a mask in Fiji, but I cannot save it in .nii format. There are so many formats, but .nii is absent. Can you help me please? 
So if my mask is not ok, can it be the reason of "input image sizes are not same'?

**Comment by ironictoo** [comment]
TWIST sequence should work, VIBE should be ok also since it is just a spoiled gradient echo as far as I know.
You can do an arbitrarily sized 4D dataset for the dynamic, no restrictions on slices. Although very large datasets with lots of slices and lots of time points take a very long time to process.
Fiji should be able to save in .nii format, if it isn't working for you you'll have to look around on the FIJI website for help. Same with the ROI, you should should be able to save as *.roi file from within the ROI manager. I don't see how this would be related to "sizes not the same error", if your images are EXACTLY the same size and you still get this error let me know.

**Comment by doctorbulat** [comment]
Now everything is clear with runA part! Thank you!

**Comment by Xueei** [comment]
I'm new here.And I have trouble with  runA part.Is directly click RUNA.fig and add dynamic datasets? Add test data which ROCKETSHIP provide? Why did I make the following  mistakes?


尝试引用非结构体数组的字段。

出错 RUNA>addfiles_Callback (line 579)
list = get(handles.DCEfilesA,'String');

出错 gui_mainfcn (line 95)
        feval(varargin{:});

出错 RUNA (line 42)
    gui_mainfcn(gui_State, varargin{:});

出错 @(hObject,eventdata)RUNA('addfiles_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating UIControl Callback
