### ISSUE TITLE
dce_run_B

### ISSUE THREAD

**Issue by doctorbulat** [petmri/ROCKETSHIP#5]
Hello! Can you explain more about injection duration please (for AIF fitting). 
The bolus arrival time is a time from the start of injection of contrast agent to the time when the contrast agent is in defined vessel? 
Is it better to put the values manually or automatically? How to do it manually? Can I get values from the graphics? Or I have to know when I injected contrast agent - 1st point?
2nd point - is the peak?

**Comment by doctorbulat** [comment]
And also I have very stupid question about results in dce_run_D part. I get quantitive results for roi in excel format after running D for Patlak and Tofts models. And the results are very different for Patlak and Tofts... Is it ok? I am not strong yet in understandidng different models. To get quantitive results do I have to put ROIs? Can I get results for all voxels?

**Comment by ironictoo** [comment]
Injection duration is how long the injection lasts. This is used to define the period between the end of the baseline and maximum concentration in the artery. From baseline to maximum concentration is modeled as a linear function, the after maximum it is an exponential decay.
For part D you can get all voxels by selecting the "fit all voxels" check box, then you will get a NIFTI image for every parameter fit (Ktrans, ve, etc..).
Patlak and Tofts can give very different results depending on your experiment design. See Sourbron 2013 (http://www.ncbi.nlm.nih.gov/pubmed/23674304) for a very thorough examination. In short Patlak assumes no backflux of Gd from the tissue back to the vessels, this assumption is violated if the leakage is high (tumors) and the study extends very long past the first bolus passage. It is generally only suitable for in special cases such as renal (Gd actively excreted), intact BBB (very low leakage rates), or first pass bolus analysis (very short time). 

    On Friday, February 5, 2016 7:57 AM, doctorbulat <notifications@github.com> wrote:
 

 And also I have very stupid question about results in dce_run_D part. I get quantitive results for roi in excel format after running D for Patlak and Tofts models. And the results are very different for Patlak and Tofts... Is it ok? I am not strong yet in understandidng different models. To get quantitive results do I have to put ROIs? Can I get results for all voxels? —
