### ISSUE TITLE
MATLAB Figure GUI error

### ISSUE THREAD

**Issue by elijahrockers** [petmri/ROCKETSHIP#6]
There seems to be some sort of wonky error with MATLAB GUI, in particular the baseline 'via figure' window that pops up to let you specify the baseline part of the curve.

It let me select the two points, but some time later it would spam this error anytime I moved the cursor over the figure:

```
Error using matlab.ui.control.UIControl/set
Invalid or deleted object.

Error in ginput>updateCrossHair (line 245)
set(crossHair, 'Visible', 'on');

Error in ginput>@(o,e)updateCrossHair(o,initialState.CrossHair) (line 201)
set(fig,'WindowButtonMotionFcn',@(o,e) updateCrossHair(o,initialState.CrossHair));
 
Error using savefig (line 36)
Error while evaluating Figure WindowButtonMotionFcn

Undefined function or variable 'ScaleFactorlv'.

Error in A_make_R1maps_func (line 789)
Adata.ScaleFactorlv = ScaleFactorlv;

Error in RUNA>done_Callback (line 372)
saved_results = A_make_R1maps_func(DYNAMIC, LV, TUMOR, NOISE, hdr, res,quant, rootname, dynampath, dynamname, aif_rr_type, ...

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in RUNA (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)RUNA('done_Callback',hObject,eventdata,guidata(hObject))
 
Error using uiwait (line 81)
Error while evaluating UIControl Callback

Error using matlab.ui.control.UIControl/set
Invalid or deleted object.

Error in ginput>updateCrossHair (line 245)
set(crossHair, 'Visible', 'on');

Error in ginput>@(o,e)updateCrossHair(o,initialState.CrossHair) (line 201)
set(fig,'WindowButtonMotionFcn',@(o,e) updateCrossHair(o,initialState.CrossHair));
 
Error using uiwait (line 81)
Error while evaluating Figure WindowButtonMotionFcn
```

**Comment by elijahrockers** [comment]
I should also note I think this error did actually interrupt process. I did this part again specifically trying to avoid the error by not moving the cursor over the figure, and it very quickly finished Part A with no error.

**Comment by ironictoo** [comment]
What version of Matlab are you using?
 

    On Monday, February 8, 2016 1:45 PM, Elijah Rockers <notifications@github.com> wrote:
 

 I should also note I think this error did actually interrupt process. I did this part again specifically trying to avoid the error by not moving the cursor over the figure, and it very quickly finished Part A with no error.—

**Comment by elijahrockers** [comment]
R2015b

**Comment by elijahrockers** [comment]
I'm wondering if those two issues are related. I am running under Ubuntu, and it's not uncommon to have problems with graphics drivers

**Comment by ironictoo** [comment]
This is probably related to your other problem, likely it is having problems so the mat file isn't written properly. I don't have ready access to version 2015b on windows or Linux so I can't readily trouble shoot this, it could be the matlab version, it could be linux. I'm trying to get a newer version installed, if that happens I'll let you know what I find.
 

    On Tuesday, February 9, 2016 9:53 AM, Elijah Rockers <notifications@github.com> wrote:
 

 I'm wondering if those two issues are related. I am running under Ubuntu, and it's not uncommon to have problems with graphics drivers—

**Comment by elijahrockers** [comment]
Closing this, as long as I don't X out of any figures, I don't see error messages (though I can see error messages if I close out some of the figures during processing)
