### ISSUE TITLE
Undefined variable "Adata" or class "Adata.quant"

### ISSUE THREAD

**Issue by elijahrockers** [petmri/ROCKETSHIP#7]
Get this error when trying to Run B. I use the results from Run A, and also a .mat file with a vector containing the time (in minutes) for each frame.

It happens even if I shut down ROCKETSHIP and start again from part B, using the results from A.

```
>> 
User selected Run B
Undefined variable "Adata" or class "Adata.quant".

Error in B_AIF_fitting_func (line 58)
quant    = Adata.quant;

Error in RUNB>done_Callback (line 375)
saved_results =
B_AIF_fitting_func(results_a_path,start_time,end_time,start_injection,end_injection,fit_aif,import_aif_path,time_resolution,
timevectpath);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in RUNB (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)RUNB('done_Callback',hObject,eventdata,guidata(hObject))
 
Error using uiwait (line 81)
Error while evaluating UIControl Callback
```

**Comment by ironictoo** [comment]
This is saying it can't find the expected data in your results from A, check part A as it isn't output proper results.
 

    On Monday, February 8, 2016 1:42 PM, Elijah Rockers <notifications@github.com> wrote:
 

 Get this error when trying to Run B I use the results from Run A, and also a mat file with a vector containing the time (in minutes) for each frameIt happens even if I shut down ROCKETSHIP and start again from part B, using the results from A>> 
User selected Run B
Undefined variable "Adata" or class "Adataquant"

Error in B_AIF_fitting_func (line 58)
quant    = Adataquant;

Error in RUNB>done_Callback (line 375)
saved_results =
B_AIF_fitting_func(results_a_path,start_time,end_time,start_injection,end_injection,fit_aif,import_aif_path,time_resolution,
timevectpath);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in RUNB (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlabgraphicsinternalfigfileFigFile/read>@(hObject,eventdata)RUNB('done_Callback',hObject,eventdata,guidata(hObject))

Error using uiwait (line 81)
Error while evaluating UIControl Callback

**Comment by elijahrockers** [comment]
It may have to do with the error from #6, because when I run part A it writes out a .mat file and also a log, containing the error from #6.

**Comment by elijahrockers** [comment]
I can get past A now with the most recent version of ROCKETSHIP
