### ISSUE TITLE
Results of A not writing correctly?

### ISSUE THREAD

**Issue by elijahrockers** [petmri/ROCKETSHIP#8]
I run part A, and the program creates a .mat of the results, A_subjectR1info.mat

It also creates a dynamicCt.nii which I assume is the concentration map of the DCE data

When I try to run part B, however, I run into trouble. Copying the Injection duration from part A does not work because Undefined variable "Adata" or class "Adata.quant".
I get the same error when I manually imput these values and try to RUN B

When I try to import A_subjectR1info.mat into matlab, it reports the .mat file is empty, so I suspect something is preventing it from writing correctly.

I would very much appreciate some help with this, I have been trying to get this thing working for months.

**Comment by ironictoo** [comment]
Are you getting errors in part A? From what you describe the results .mat file from a is empty so there must be something in A that is going wrong and it isn't writing the results file. Take a closer look at part A, let me know what you find. 

Sam

**Comment by elijahrockers** [comment]
Only error in the log is a warning. No open gl, so possible graphics issues
(al tough I forced open gl and did not seem to have any problems with the
figures). May have something to do with the fact I'm using 2015b

I can see the aif and voi figures and log didn't have any errors. I'll fork
the git and see what I can find when I get a chance, but for now I'm gonna
try the osirix plugins, supervisor's orders.

**Comment by elijahrockers** [comment]
Osirix plugin is not going to be sufficient for our needs.

I see one of the most recent updates to A_make_R1maps_func was to the .mat saving functionality. Think this might contribute to the problem in some way?

**Comment by elijahrockers** [comment]
I downloaded the latest version of ROCKETSHIP and reinstalled. This part seems to be working OK now.
