### ISSUE TITLE
Problem using T1 Multi FA Exponential in fittin_gui 

### ISSUE THREAD

**Issue by nquartuccio** [petmri/ROCKETSHIP#9]
Dear all,
I am encountering the following problem and could not solve it despite several efforts.

I  am running the fitting_gui in MATLAB R2014a.
I have uploaded a single merged file (VFA3, VFA13, VFA18 and VFAdyb); data order is X,Y,Z,N.
Number of CPUs set as 1. in the line of value list I have inserted 3,13,18; TR : 12; XY Smooth Size is 0. The box of Fit all voxels is ticked.
Everything goes smoothly without any problem selecting T1 Multi FA Linear but got error message and don't get any T1 map when selecting T1 Multi FA Exponential as follows: 
Error using fitParameter (line 341)
An UndefinedFunction error was thrown on the workers for 'fitoptions'.  This might be because the file
containing 'fitoptions' is not accessible on the workers.  Use addAttachedFiles(pool, files) to
specify the required files to be attached.  See the documentation for 'parallel.Pool/addAttachedFiles'
for more details.

Error in parallelFit>(parfor body) (line 38)
        fit_output(m,:) = fitParameter(parameter,fit_type,si,tr, fit_name, ncoeffs, coeffs,
        tr_present,rsquared_threshold);

Error in parallelFit (line 32)
    parfor m = n:min(n+(parallel_size-1),number_voxels)

Error in calculateMap (line 475)
            fit_output = parallelFit(parameter_list,fit_type,shaped_image,tr, submit, fit_file,
            ncoeffs, coeffs, tr_present,rsquared_threshold);

Error in calculateMap_batch (line 54)
            [single_IMG, errormsg_ind, CUR_JOB, new_txtname(done+1).txtname] = calculateMap(CUR_JOB,
            i);

Error in fitting_gui>ok_button_Callback (line 307)
[single_IMG submit data_setnum] = calculateMap_batch(JOB_struct, submit, dataset_to_process);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in fitting_gui (line 43)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)fitting_gui('ok_button_Callback',hObject,eventdata,guidata(hObject))

Caused by:
    Undefined function 'fitoptions' for input arguments of type 'char'.

Error while evaluating uicontrol Callback

---

I tried also splitting the merged file and uploading to the fitting gui just the VFAs and changing the order to /File getting this error messages:
Subscripted assignment dimension mismatch.

Error in calculateMap (line 283)
            shaped_image(:,:,:,m) = image_3d;

Error in calculateMap_batch (line 54)
            [single_IMG, errormsg_ind, CUR_JOB, new_txtname(done+1).txtname] = calculateMap(CUR_JOB,
            i);

Error in fitting_gui>ok_button_Callback (line 307)
[single_IMG submit data_setnum] = calculateMap_batch(JOB_struct, submit, dataset_to_process);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in fitting_gui (line 43)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)fitting_gui('ok_button_Callback',hObject,eventdata,guidata(hObject))

Error while evaluating uicontrol Callback

Could anyone provide the solution?

Best regards
Natale

**Comment by ironictoo** [comment]
It sounds like you don't have the required tool boxes (curve fitting toolbox I believe), do you have access to that toolbox?

Sam

**Comment by nquartuccio** [comment]
I think I have access, I can attach the screenshots or even provide the files if you want  to a have a try.

![capture1](https://cloud.githubusercontent.com/assets/19269862/15172931/de66a804-1750-11e6-99e3-acc495d0d4f9.JPG)
![capture2](https://cloud.githubusercontent.com/assets/19269862/15172932/de6affc6-1750-11e6-8be3-cb62a121bee2.JPG)

Natale

**Comment by ironictoo** [comment]
Did you ever get this solved? It still looks to me like the first error is from not having the tool boxes and the second error looks like the three files you input have different matrix sizes. Did you double check both of these?

**Comment by nquartuccio** [comment]
Thaks but, I’m still struggling.  I believe the matrix size look the same to me.
I’ll speak tomorrow with the physicist.
I am testing also different softwares at the moment
Best regards
NQ
